name: Criterion push / merge CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependecies
        run: sudo apt install gcc make
      - name: Build
        run: make
      - name: Run tests
        run: ./criterion

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/release'
    steps:
      - uses: actions/checkout@v2
      - name: Install dependecies
        run: sudo apt install gcc make
      - name: Create release zip
        run: zip criterion.zip criterion * -x "*.git*" -x "*.github*"
      - name: Build
        run: make
      - name: Run tests
        run: ./criterion

    - name: Create GitHub release
      id: create-new-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_number }}
        release_name: Release ${{ github.run_number }}

    - name: View content
      run: ls -lR
    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-new-release.outputs.upload_url }}
        asset_path: ./criterion.zip
        asset_name: site-v${{ github.run_number }}.zip
        asset_content_type: application/zip

    - name: Upload release asset binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-new-release.outputs.upload_url }}
        asset_path: ./criterion
        asset_name: criterion-v${{ github.run_number }}
        asset_content_type: application/zip
