name: Criterion push / merge CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependecies
        run: sudo apt install gcc make
      - name: Build
        run: make
      - name: Run tests
        run: ./criterion

